tail.writer.strings = {
    es: {
        chars: "Caracteres",
        lines: "Lineas",
        words: "Palabras",

        // Markups
        bbcode: "BBCode",
        markdown: "Markdown",
        textile: "Textile",

        // Actions
        about: "Acerca de",
        aboutDevelop: "Desarrollado por $1",
        aboutDesc1: "Escrito en JavaScript puro de vainilla",
        aboutDesc2: "publicado bajo la licencia MIT",
        aboutDesign: "Diseñado con $1",
        aboutLink1: "GitHub Repositorio",
        aboutLink2: "Documentacion",
        aboutLink3: "Demonstracion",
        aboutLink4: "Reportar un Error",
        fullscreen: "Alternar pantalla completa",
        indent: "Sangrar",
        markup: "Cambio de marca",
        modeWrite: "Escribir",
        modePreview: "Vista Previa",
        outdent: "Quitar Sangria",
        preview: "Vista previa de alternancia",
        previewEmpty: "¡No hay nada que previsualizar todavía!",

        // Debug
        errorAction: "¡La acción pasada es desconocida!",
        errorMarkup: "El marcado pasado no existe!",

        // Markups
        acronym: "Acrónimo",
        big: "Grande",
        bold: "Negrita",
        center: "Parráfo Central",
        cite: "Citación",
        code: "Codigo (En linea)",
        codeblock: "Codigo (Bloque)",
        color: "Color de Texto",
        definition: "Lista de Definiciones",
        emphasize: "Enfatizar",
        email: "Correo Electrónico",
        emailAddress: "Direccion de Correo Electrónico",
        emailButton: "Insertar enlace de correo electrónico",
        emailTitle: "Título de Correo Electrónico",
        font: "Familia tipográfica",
        header: "Titulo",
        headers: "Títulos",
        hr: "Regla Horizontal",
        image: "Imagen",
        imageButton: "Incrustar Imagen",
        imageTitle: "Titulo de Imagen",
        imageURL: "URL de Imagen",
        italic: "Cursiva",
        justify: "Justificar Párrafo",
        left: "Párrafo izquierdo",
        link: "Hiperenlace",
        linkNewTab: "Abrir enlace en una nueva pestaña",
        linkButton: "Incrustar Enlace",
        linkTitle: "Título de Enlace",
        linkURL: "URL de Enlace",
        listOrdered: "Lista ordenada",
        listUnordered: "Lista desordenada",
        listChecked: "Lista seleccionada",
        listUnchecked: "Lista deseleccionada",
        pre: "Texto pre-formateado",
        quote: "Blockquote",
        right: "Párrafo derecho",
        size: "Tamaño de texto",
        small: "Pequeño",
        span: "Span",
        strikethrough: "Tachado",
        strong: "Negrita",
        sub: "Subindice",
        sup: "Superindice",
        table: "Tabla",
        tableButton: "Incrustar Tabla",
        tableHeader: "Agregar Encabezado de Tabla",
        tableFooter: "Agregar pie de páginade Tabla",
        tableCols: "Columnas",
        tableRows: "Filas",
        underline: "Subrayar"
    }
};