<?php
return [

    /**
     * LENGHT GENERATE STRING HASH
     * ---------------------------
     * integer | int
     */
    'min_lenght' => 5,

    /*
     * APLHABET USED IN HASHID GENERATE
     * --------------------------------
     * string
     */
    'alphabet'   => 'I76KTDKWGEZALYTCPHCGIBL5LPHY0MXBJRD0IBK8J0N2ELIL0P7PJFDTVC1KICAWZNHBD1QNJPGT9X2OZSZ6TKX77RHBMDHBNNIMDSEPATITCMRKUNM765RJU2UTEEDFSBMPMRPA3AJCNIPMJWUS6BGJHGUUWXYJN3LTZCJLUJTHDO3SUSZ1',

];
